# Generated by Django 2.1.2 on 2018-11-29 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('imgMascota', models.ImageField(upload_to='mascotas/')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaNac', models.DateField()),
                ('telContacto', models.CharField(max_length=8)),
                ('region', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15)),
                ('tipoVivienda', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
