# Generated by Django 2.1.2 on 2018-11-05 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregarAdoptante',
            fields=[
                ('nombreUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=20)),
                ('fechaNac', models.DateTimeField()),
                ('telContacto', models.IntegerField(max_length=8)),
                ('region', models.CharField(max_length=1)),
                ('ciudad', models.CharField(max_length=1)),
                ('tipoVivienda', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(default='Adoptante', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
