# Generated by Django 2.1.2 on 2018-11-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregaradoptante',
            name='telContacto',
            field=models.IntegerField(),
        ),
    ]
