# Generated by Django 2.1.2 on 2018-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_auto_20181105_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregaradoptante',
            name='ciudad',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agregaradoptante',
            name='fechaNac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agregaradoptante',
            name='region',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agregaradoptante',
            name='tipoVivienda',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
