# Generated by Django 2.1.2 on 2018-11-07 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0004_auto_20181105_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgregarAdoptante',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telContacto',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoVivienda',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
