# Generated by Django 2.1.2 on 2018-11-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0005_auto_20181106_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
    ]
