# Generated by Django 2.1 on 2018-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0006_remove_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('imgMascota', models.ImageField(upload_to='fotos/')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(),
        ),
    ]
