# Generated by Django 2.1.2 on 2018-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0015_auto_20181111_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='idMascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
