# Generated by Django 2.1.2 on 2018-11-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0016_auto_20181126_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
