# Generated by Django 2.1.2 on 2018-11-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0019_auto_20181128_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
